import type { NextPage } from 'next'
import Head from 'next/head'
import Beranda from '../components/UI/template/Beranda'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Beranda />
    </div>
  )
}

export default Home
